name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/practicekotlin:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/practicekotlin:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2
      uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_default_region: us-east-1
        aws_elb_app_port: 8080
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/practicekotlin:latest
          docker stop practicekotlin || true
          docker rm practicekotlin || true
          docker run -d -p 8080:8080 --name practicekotlin ${{ secrets.DOCKER_USERNAME }}/practicekotlin:latest

#        host: ${{ secrets.EC2_HOST }}
#        username: ${{ secrets.EC2_USER }}
#        key: ${{ secrets.EC2_SSH_KEY }}